"""Generate the reviewed endpoint schema and TypeScript types from FastAPI."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def _name(value: str) -> str:
    return value.rsplit("/", 1)[-1].replace("-", "_")


def _typescript(schema: dict[str, Any]) -> str:
    if set(schema) <= {"title", "description"}:
        return "unknown"
    if "$ref" in schema:
        return _name(schema["$ref"])
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(item) for item in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(_typescript(item) for item in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{_typescript(schema['items'])}>"
    if kind == "object":
        if not schema.get("properties"):
            return "Record<string, unknown>"
        required = schema.get("required", [])
        return (
            "{\n"
            + "\n".join(
                f"  {key}{'' if key in required else '?'}: {_typescript(value)};"
                for key, value in schema.get("properties", {}).items()
            )
            + "\n}"
        )
    if kind in {"string", "number", "boolean", "null"}:
        return str(kind)
    if kind == "integer":
        return "number"
    raise ValueError("unhandled schema kind; review generator before changing contract")


def contract_artifacts() -> tuple[str, str]:
    from trafriend_api.main import create_app
    from trafriend_api.settings import Settings

    schema = create_app(Settings()).openapi()
    paths = {
        path: value
        for path, value in schema["paths"].items()
        if path
        in {"/api/v1/profit-ratio/universe/search", "/api/v1/profit-ratio/symbols/{symbol}/daily"}
    }
    definitions: dict[str, Any] = {}

    def collect(value: Any) -> None:
        if isinstance(value, dict):
            if "$ref" in value:
                name = value["$ref"].rsplit("/", 1)[-1]
                if name not in definitions:
                    definitions[name] = schema["components"]["schemas"][name]
                    collect(definitions[name])
            for child in value.values():
                collect(child)
        elif isinstance(value, list):
            for child in value:
                collect(child)

    collect(paths)
    snapshot = {
        "openapi": schema["openapi"],
        "info": schema["info"],
        "paths": paths,
        "components": {"schemas": definitions},
    }
    types = "// Generated by export_profit_ratio_contract; do not edit manually.\n\n"
    for name, definition in sorted(definitions.items()):
        types += f"export type {_name(name)} = {_typescript(definition)};\n\n"
    types += "export type ProfitRatioConstituent = NasdaqConstituent;\n"
    return json.dumps(snapshot, indent=2, sort_keys=True) + "\n", types


def main() -> None:
    root = Path(__file__).resolve().parents[5]
    schema, types = contract_artifacts()
    snapshot_path = root / "services/api/openapi-profit-ratio.json"
    types_path = root / "apps/web/src/lib/api/generated/profit-ratio.ts"
    types_path.parent.mkdir(parents=True, exist_ok=True)
    snapshot_path.write_text(schema)
    types_path.write_text(types)
    print("Profit Ratio contract generated")


if __name__ == "__main__":
    main()
