"""Verified normalized QQQ equity identity snapshot, not licensed price data.

Issuer effectiveBusinessDate: 2026-09-04; checked against the live Invesco
QQQ holdings endpoint on 2026-09-08. Cash/futures/collateral are excluded.
This dated bootstrap is not a claim of perpetual or historical NDX membership.
Source: https://www.invesco.com/qqq-etf/en/about.html
"""

from datetime import date

from trafriend_api.domain.profit_ratio_daily import NasdaqConstituent

AS_OF = date(2026, 9, 4)
SOURCE = "QQQ_EQUITY_HOLDINGS:Invesco"
ROWS = (
    ("ins_aapl_xnas", "AAPL", "Apple Inc"),
    ("ins_cusip_009066101", "ABNB", "Airbnb Inc"),
    ("ins_adbe_xnas", "ADBE", "Adobe Inc"),
    ("ins_adi_xnas", "ADI", "Analog Devices Inc"),
    ("ins_cusip_053015103", "ADP", "Automatic Data Processing Inc"),
    ("ins_cusip_052769106", "ADSK", "Autodesk Inc"),
    ("ins_cusip_025537101", "AEP", "American Electric Power Co Inc"),
    ("ins_alab_xnas", "ALAB", "Astera Labs Inc"),
    ("ins_cusip_02043q107", "ALNY", "Alnylam Pharmaceuticals Inc"),
    ("ins_amat_xnas", "AMAT", "Applied Materials Inc"),
    ("ins_amd_xnas", "AMD", "Advanced Micro Devices Inc"),
    ("ins_cusip_031162100", "AMGN", "Amgen Inc"),
    ("ins_amzn_xnas", "AMZN", "Amazon.com Inc"),
    ("ins_app_xnas", "APP", "AppLovin Corp"),
    ("ins_arm_xnas", "ARM", "ARM Holdings PLC"),
    ("ins_asml_xnas", "ASML", "ASML Holding NV"),
    ("ins_avgo_xnas", "AVGO", "Broadcom Inc"),
    ("ins_cusip_05464c101", "AXON", "Axon Enterprise Inc"),
    ("ins_cusip_09857l108", "BKNG", "Booking Holdings Inc"),
    ("ins_cusip_05722g100", "BKR", "Baker Hughes Co"),
    ("ins_cusip_g25839104", "CCEP", "Coca-Cola Europacific Partners PLC"),
    ("ins_cdns_xnas", "CDNS", "Cadence Design Systems Inc"),
    ("ins_ceg_xnas", "CEG", "Constellation Energy Corp"),
    ("ins_cusip_20030n101", "CMCSA", "Comcast Corp"),
    ("ins_cost_xnas", "COST", "Costco Wholesale Corp"),
    ("ins_cusip_217204106", "CPRT", "Copart Inc"),
    ("ins_crwd_xnas", "CRWD", "Crowdstrike Holdings Inc"),
    ("ins_crwv_xnas", "CRWV", "CoreWeave Inc"),
    ("ins_csco_xnas", "CSCO", "Cisco Systems Inc"),
    ("ins_cusip_126408103", "CSX", "CSX Corp"),
    ("ins_cusip_172908105", "CTAS", "Cintas Corp"),
    ("ins_cusip_25809k105", "DASH", "DoorDash Inc"),
    ("ins_cusip_23804l103", "DDOG", "Datadog Inc"),
    ("ins_cusip_252131107", "DXCM", "Dexcom Inc"),
    ("ins_cusip_30161n101", "EXC", "Exelon Corp"),
    ("ins_cusip_25278x109", "FANG", "Diamondback Energy Inc"),
    ("ins_cusip_311900104", "FAST", "Fastenal Co"),
    ("ins_cusip_n3168p101", "FER", "Ferrovial NV"),
    ("ins_cusip_34959e109", "FTNT", "Fortinet Inc"),
    ("ins_cusip_36266g107", "GEHC", "GE HealthCare Technologies Inc"),
    ("ins_cusip_375558103", "GILD", "Gilead Sciences Inc"),
    ("ins_goog_xnas", "GOOG", "Alphabet Inc Class C"),
    ("ins_googl_xnas", "GOOGL", "Alphabet Inc Class A"),
    ("ins_hon_xnas", "HON", "Honeywell International Inc"),
    ("ins_cusip_43849r105", "HONA", "Honeywell Aerospace Inc"),
    ("ins_cusip_45168d104", "IDXX", "IDEXX Laboratories Inc"),
    ("ins_intc_xnas", "INTC", "Intel Corp"),
    ("ins_cusip_461202103", "INTU", "Intuit Inc"),
    ("ins_isrg_xnas", "ISRG", "Intuitive Surgical Inc"),
    ("ins_cusip_49271v100", "KDP", "Keurig Dr Pepper Inc"),
    ("ins_cusip_500754106", "KHC", "Kraft Heinz Co/The"),
    ("ins_klac_xnas", "KLAC", "KLA Corp"),
    ("ins_cusip_g54950103", "LIN", "Linde PLC"),
    ("ins_lite_xnas", "LITE", "Lumentum Holdings Inc"),
    ("ins_lrcx_xnas", "LRCX", "Lam Research Corp"),
    ("ins_cusip_571903202", "MAR", "Marriott International Inc/MD"),
    ("ins_mchp_xnas", "MCHP", "Microchip Technology Inc"),
    ("ins_cusip_609207105", "MDLZ", "Mondelez International Inc"),
    ("ins_meli_xnas", "MELI", "MercadoLibre Inc"),
    ("ins_meta_xnas", "META", "Meta Platforms Inc"),
    ("ins_mnst_xnas", "MNST", "Monster Beverage Corp"),
    ("ins_mpwr_xnas", "MPWR", "Monolithic Power Systems Inc"),
    ("ins_mrvl_xnas", "MRVL", "Marvell Technology Inc"),
    ("ins_msft_xnas", "MSFT", "Microsoft Corp"),
    ("ins_mstr_xnas", "MSTR", "Strategy Inc"),
    ("ins_mu_xnas", "MU", "Micron Technology Inc"),
    ("ins_nbis_xnas", "NBIS", "Nebius Group NV"),
    ("ins_nflx_xnas", "NFLX", "Netflix Inc"),
    ("ins_nvda_xnas", "NVDA", "NVIDIA Corp"),
    ("ins_nxpi_xnas", "NXPI", "NXP Semiconductors NV"),
    ("ins_cusip_679580100", "ODFL", "Old Dominion Freight Line Inc"),
    ("ins_cusip_67103h107", "ORLY", "O'Reilly Automotive Inc"),
    ("ins_panw_xnas", "PANW", "Palo Alto Networks Inc"),
    ("ins_cusip_704326107", "PAYX", "Paychex Inc"),
    ("ins_cusip_693718108", "PCAR", "PACCAR Inc"),
    ("ins_pdd_xnas", "PDD", "PDD Holdings Inc"),
    ("ins_cusip_713448108", "PEP", "PepsiCo Inc"),
    ("ins_pltr_xnas", "PLTR", "Palantir Technologies Inc"),
    ("ins_pypl_xnas", "PYPL", "PayPal Holdings Inc"),
    ("ins_qcom_xnas", "QCOM", "QUALCOMM Inc"),
    ("ins_cusip_75886f107", "REGN", "Regeneron Pharmaceuticals Inc"),
    ("ins_rklb_xnas", "RKLB", "Rocket Lab Corp"),
    ("ins_cusip_776696106", "ROP", "Roper Technologies Inc"),
    ("ins_cusip_778296103", "ROST", "Ross Stores Inc"),
    ("ins_cusip_855244109", "SBUX", "Starbucks Corp"),
    ("ins_shop_xnas", "SHOP", "Shopify Inc"),
    ("ins_sndk_xnas", "SNDK", "Sandisk Corp"),
    ("ins_cusip_871607107", "SNPS", "Synopsys Inc"),
    ("ins_spcx_xnas", "SPCX", "Space Exploration Technologies Corp"),
    ("ins_stx_xnas", "STX", "Seagate Technology Holdings PLC"),
    ("ins_ter_xnas", "TER", "Teradyne Inc"),
    ("ins_cusip_872590104", "TMUS", "T-Mobile US Inc"),
    ("ins_cusip_884903881", "TRI", "Thomson Reuters Corp"),
    ("ins_tsla_xnas", "TSLA", "Tesla Inc"),
    ("ins_cusip_874054109", "TTWO", "Take-Two Interactive Software Inc"),
    ("ins_txn_xnas", "TXN", "Texas Instruments Inc"),
    ("ins_cusip_92532f100", "VRTX", "Vertex Pharmaceuticals Inc"),
    ("ins_cusip_934423104", "WBD", "Warner Bros Discovery Inc"),
    ("ins_cusip_98138h101", "WDAY", "Workday Inc"),
    ("ins_wdc_xnas", "WDC", "Western Digital Corp"),
    ("ins_cusip_931142103", "WMT", "Walmart Inc"),
    ("ins_cusip_98389b100", "XEL", "Xcel Energy Inc"),
)


def bootstrap_constituents() -> tuple[NasdaqConstituent, ...]:
    return tuple(NasdaqConstituent(identity, symbol, name, AS_OF, SOURCE)
                 for identity, symbol, name in ROWS)
