# ruff: noqa: E501
"""expand the active verified single-stock leveraged universe

Revision ID: 20260907_0007
Revises: 20260907_0006
Create Date: 2026-09-07

This point-in-time snapshot adds active U.S.-listed daily single-stock leveraged
and inverse products outside the September Top-100-focused catalog. Candidates
were discovered in Alpaca's active U.S. equity asset catalog, matched only when
the product name explicitly identified an active underlying symbol and daily
factor, and checked against the corresponding issuer's official catalog.

Index, basket, sector, commodity, crypto, income, monthly, and quarterly products
are intentionally excluded. Relationships are never inferred from ticker names.
"""

from datetime import date, datetime, timezone
from typing import Optional, Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import insert

revision: str = "20260907_0007"
down_revision: Optional[str] = "20260907_0006"
branch_labels: Optional[Union[str, Sequence[str]]] = None
depends_on: Optional[Union[str, Sequence[str]]] = None

VERIFIED_AT = datetime(2026, 9, 7, 22, tzinfo=timezone.utc)
EFFECTIVE_FROM = date(2026, 9, 4)

ISSUER_SOURCES = {
    "Corgi": "https://corgiinvest.com/2xleveraged",
    "Defiance": "https://www.defianceetfs.com/prospectuses/",
    "Direxion": "https://www.direxion.com/single-stock-etfs",
    "GraniteShares": "https://graniteshares.com/etfs/leveraged/",
    "KraneShares": (
        "https://engage.kraneshares.com/s/ca5f6a4a/"
        "kraneshares-single-stock-levered-etf-suite/"
    ),
    "Leverage Shares": (
        "https://leverageshares.com/us/all-etfs?category=Daily+Leveraged"
    ),
    "T-REX": "https://www.rexshares.com/t-rex-leveraged-etfs/",
    "Tradr ETFs": "https://www.tradretfs.com/",
}

# symbol, display name, exchange MIC
UNDERLYINGS = (
    ("AAL", "American Airlines Group Inc. Common Stock", "XNAS"),
    ("AAOI", "Applied Optoelectronics, Inc. Common Stock", "XNAS"),
    ("ACHR", "Archer Aviation Inc.", "XNYS"),
    ("ACLS", "Axcelis Technologies, Inc. Common Stock", "XNAS"),
    ("ACMR", "ACM Research, Inc. Class A Common Stock", "XNAS"),
    ("AEHR", "Aehr Test Systems Common Stock", "XNAS"),
    ("AFRM", "Affirm Holdings, Inc. Class A Common Stock", "XNAS"),
    ("AKAM", "Akamai Technologies, Inc. Common Stock", "XNAS"),
    ("ALB", "Albemarle Corporation", "XNYS"),
    ("AMKR", "Amkor Technology, Inc. Common Stock", "XNAS"),
    ("AMPX", "Amprius Technologies, Inc.", "XNYS"),
    ("ANET", "Arista Networks", "XNYS"),
    ("APLD", "Applied Digital Corporation Common Stock", "XNAS"),
    ("ARM", "Arm Holdings plc American Depositary Shares", "XNAS"),
    ("ASTS", "AST SpaceMobile, Inc. Class A Common Stock", "XNAS"),
    ("AVAV", "AeroVironment, Inc. Common Stock", "XNAS"),
    ("AXTI", "AXT Inc Common Stock", "XNAS"),
    ("BABA", "Alibaba Group Holding Limited American Depositary Shares, each represents eight Ordinary Shares", "XNYS"),
    ("BB", "BlackBerry Limited", "XNYS"),
    ("BBAI", "BigBear.ai Holdings, Inc.", "XNYS"),
    ("BIDU", "Baidu, Inc. ADS", "XNAS"),
    ("BLSH", "Bullish", "XNYS"),
    ("BTDR", "Bitdeer Technologies Group Class A Ordinary Shares", "XNAS"),
    ("BULL", "Webull Corporation Class A Ordinary Shares", "XNAS"),
    ("CAMT", "Camtek Ltd. Ordinary Shares", "XNAS"),
    ("CART", "Maplebear Inc. Common Stock", "XNAS"),
    ("CDNS", "Cadence Design Systems, Inc. Common Stock", "XNAS"),
    ("CEG", "Constellation Energy Corporation Common Stock", "XNAS"),
    ("CIFR", "Cipher Digital Inc. Common Stock", "XNAS"),
    ("CLS", "Celestica, Inc.", "XNYS"),
    ("CLSK", "CleanSpark, Inc. Common Stock", "XNAS"),
    ("CORZ", "Core Scientific, Inc. Common Stock", "XNAS"),
    ("CPNG", "Coupang, Inc.", "XNYS"),
    ("CRML", "Critical Metals Corp. Ordinary Shares", "XNAS"),
    ("CRUS", "Cirrus Logic, Inc. Common Stock", "XNAS"),
    ("DJT", "Trump Media & Technology Group Corp. Common Stock", "XNAS"),
    ("DOCN", "DigitalOcean Holdings, Inc.", "XNYS"),
    ("DUOL", "Duolingo, Inc. Class A Common Stock", "XNAS"),
    ("ECHO", "EchoStar Corporation Common Stock", "XNAS"),
    ("ENTG", "Entegris, Inc. Common Stock", "XNAS"),
    ("EOSE", "Eos Energy Enterprises, Inc. Class A Common Stock", "XNAS"),
    ("ETN", "Eaton Corporation, plc Ordinary Shares", "XNYS"),
    ("FCX", "Freeport-McMoran Inc.", "XNYS"),
    ("FIG", "Figma, Inc.", "XNYS"),
    ("FIGR", "Figure Technology Solutions, Inc. Class A Common Stock", "XNAS"),
    ("FIX", "Comfort Systems USA, Inc.", "XNYS"),
    ("FLEX", "Flex Ltd. Ordinary Shares", "XNAS"),
    ("FLY", "Firefly Aerospace Inc. Common Stock", "XNAS"),
    ("FN", "Fabrinet", "XNYS"),
    ("FORM", "FormFactor, Inc. FormFactor, Inc. Common Stock", "XNAS"),
    ("FPS", "Forgent Power Solutions, Inc.", "XNYS"),
    ("FUTU", "Futu Holdings Limited American Depositary Shares", "XNAS"),
    ("GEMI", "Gemini Space Station, Inc. Class A Common Stock", "XNAS"),
    ("GFS", "GlobalFoundries Inc. Ordinary Shares", "XNAS"),
    ("GLXY", "Galaxy Digital Inc. Class A Common Stock", "XNAS"),
    ("GME", "GameStop Corp. Class A", "XNYS"),
    ("GRAB", "Grab Holdings Limited Class A Ordinary Shares", "XNAS"),
    ("HIMS", "Hims & Hers Health, Inc.", "XNYS"),
    ("HON", "Honeywell International Inc. Common Stock", "XNAS"),
    ("HUT", "Hut 8 Corp. Common Stock", "XNAS"),
    ("IBM", "International Business Machines Corporation", "XNYS"),
    ("INFQ", "Infleqtion, Inc.", "XNYS"),
    ("IONQ", "IonQ, Inc.", "XNYS"),
    ("ISRG", "Intuitive Surgical, Inc. Common Stock", "XNAS"),
    ("JBL", "Jabil Inc.", "XNYS"),
    ("JD", "JD.com, Inc. American Depositary Shares", "XNAS"),
    ("JOBY", "Joby Aviation, Inc.", "XNYS"),
    ("KEEL", "Keel Infrastructure Corp. Common Stock", "XNAS"),
    ("KEYS", "Keysight Technologies, Inc.", "XNYS"),
    ("KTOS", "Kratos Defense & Security Solutions, Inc. Common Stock", "XNAS"),
    ("LASR", "nLIGHT, Inc. Common Stock", "XNAS"),
    ("LEU", "Centrus Energy Corp.", "XNYS"),
    ("LMT", "Lockheed Martin Corp.", "XNYS"),
    ("LRN", "Stride, Inc.", "XNYS"),
    ("LUNR", "Intuitive Machines, Inc. Class A Common Stock", "XNAS"),
    ("LWLG", "Lightwave Logic, Inc. Common Stock", "XNAS"),
    ("MARA", "MARA Holdings, Inc. Common Stock", "XNAS"),
    ("MCHP", "Microchip Technology Incorporated Common Stock", "XNAS"),
    ("MELI", "MercadoLibre, Inc. Common Stock", "XNAS"),
    ("MNST", "Monster Beverage Corporation", "XNAS"),
    ("MP", "MP Materials Corp.", "XNYS"),
    ("MPWR", "Monolithic Power Systems, Inc. Common Stock", "XNAS"),
    ("MRAM", "Everspin Technologies, Inc. Common Stock", "XNAS"),
    ("MSI", "Motorola Solutions, Inc. New", "XNYS"),
    ("MTSI", "MACOM Technology Solutions Holdings, Inc. Common Stock", "XNAS"),
    ("MXL", "MaxLinear, Inc. Common Stock", "XNAS"),
    ("NEM", "Newmont Corporation", "XNYS"),
    ("NET", "Cloudflare, Inc. Class A common stock, par value $0.001 per share", "XNYS"),
    ("NIO", "NIO Inc. American depositary shares, each representing one Class A ordinary share", "XNYS"),
    ("NOK", "Nokia Corporation", "XNYS"),
    ("NTAP", "NetApp, Inc. Common Stock", "XNAS"),
    ("NVO", "Novo-Nordisk A/S", "XNYS"),
    ("NVTS", "Navitas Semiconductor Corporation Common Stock", "XNAS"),
    ("NXPI", "NXP Semiconductors N.V. Common Stock", "XNAS"),
    ("OKLO", "Oklo Inc.", "XNYS"),
    ("OKTA", "Okta, Inc. Class A Common Stock", "XNAS"),
    ("ON", "ON Semiconductor Corporation Common Stock", "XNAS"),
    ("ONDS", "Ondas Inc. Common Stock", "XNAS"),
    ("ONTO", "Onto Innovation Inc.", "XNYS"),
    ("OPEN", "Opendoor Technologies Inc Common Stock", "XNAS"),
    ("OSCR", "Oscar Health, Inc.", "XNYS"),
    ("OSS", "One Stop Systems, Inc. Common Stock", "XNAS"),
    ("OUST", "Ouster, Inc. Common Stock", "XNAS"),
    ("P", "Everpure, Inc.", "XNYS"),
    ("PBR", "PETROLEO BRASILEIRO S.A.-PETROBRAS ADS (REP 1 COMMON SHARE)", "XNYS"),
    ("PDD", "PDD Holdings Inc. American Depositary Shares", "XNAS"),
    ("PENG", "Penguin Solutions, Inc. Common Stock", "XNAS"),
    ("PL", "Planet Labs PBC", "XNYS"),
    ("PLUG", "Plug Power, Inc. Common Stock", "XNAS"),
    ("POET", "POET Technologies Inc. Common Shares", "XNAS"),
    ("PONY", "Pony AI Inc. American Depositary Shares", "XNAS"),
    ("PURR", "Hyperliquid Strategies Inc Common Stock", "XNAS"),
    ("PYPL", "PayPal Holdings, Inc. Common Stock", "XNAS"),
    ("QBTS", "D-Wave Quantum Inc. Common Stock", "XNAS"),
    ("QNT", "Quantinuum Inc. Class A Common Stock", "XNAS"),
    ("QS", "QuantumScape Corporation Class A Common Stock", "XNAS"),
    ("QUBT", "Quantum Computing Inc. Common Stock", "XNAS"),
    ("RBLX", "Roblox Corporation", "XNYS"),
    ("RCAT", "Red Cat Holdings, Inc. Common Stock", "XNAS"),
    ("RDDT", "Reddit, Inc.", "XNYS"),
    ("RDW", "Redwire Corporation", "XNYS"),
    ("RGTI", "Rigetti Computing, Inc. Common Stock", "XNAS"),
    ("RIOT", "Riot Platforms, Inc. Common Stock", "XNAS"),
    ("RIVN", "Rivian Automotive, Inc. Class A Common Stock", "XNAS"),
    ("RMBS", "Rambus Inc. Common Stock", "XNAS"),
    ("RTX", "RTX Corporation", "XNYS"),
    ("SBET", "SharpLink, Inc. Common Stock", "XNAS"),
    ("SIMO", "Silicon Motion Technology Corporation American Depositary Shares", "XNAS"),
    ("SITM", "SiTime Corporation Common Stock", "XNAS"),
    ("SMR", "NuScale Power Corporation", "XNYS"),
    ("SMTC", "Semtech Corporation Common Stock", "XNAS"),
    ("SNAP", "Snap Inc.", "XNYS"),
    ("SOFI", "SoFi Technologies, Inc. Common Stock", "XNAS"),
    ("SOUN", "SoundHound AI, Inc Class A Common Stock", "XNAS"),
    ("SPOT", "Spotify Technology S.A.", "XNYS"),
    ("STM", "STMicroelectronics N.V.", "XNYS"),
    ("STRL", "Sterling Infrastructure, Inc. Common Stock", "XNAS"),
    ("TDC", "TERADATA CORPORATION", "XNYS"),
    ("TE", "T1 Energy Inc.", "XNYS"),
    ("TEL", "TE Connectivity plc", "XNYS"),
    ("TEM", "Tempus AI, Inc. Class A Common Stock", "XNAS"),
    ("TER", "Teradyne, Inc. Common Stock", "XNAS"),
    ("TPL", "Texas Pacific Land Corporation", "XNYS"),
    ("TSEM", "Tower Semiconductor Ltd. Ordinary Shares", "XNAS"),
    ("TTD", "The Trade Desk, Inc. Class A Common Stock", "XNAS"),
    ("TTMI", "TTM Technologies, Inc. Common Stock", "XNAS"),
    ("U", "Unity Software Inc.", "XNYS"),
    ("UCTT", "Ultra Clean Holdings, Inc. Common Stock", "XNAS"),
    ("UEC", "Uranium Energy Corp.", "XASE"),
    ("UMAC", "Unusual Machines, Inc.", "XASE"),
    ("UMC", "United Microelectronic Corp.", "XNYS"),
    ("UPST", "Upstart Holdings, Inc. Common stock", "XNAS"),
    ("USAR", "USA Rare Earth, Inc. Class A Common Stock", "XNAS"),
    ("UUUU", "Energy Fuels Inc.", "XASE"),
    ("VALE", "VALE S.A.", "XNYS"),
    ("VELO", "Velo3D, Inc. Common Stock", "XNAS"),
    ("VIAV", "Viavi Solutions Inc. Common Stock", "XNAS"),
    ("VST", "Vistra Corp.", "XNYS"),
    ("WULF", "TeraWulf Inc. Common Stock", "XNAS"),
    ("WYFI", "WhiteFiber, Inc. Ordinary Shares", "XNAS"),
    ("XNDU", "Xanadu Quantum Technologies Limited Class B Subordinate Voting Shares", "XNAS"),
    ("XPEV", "XPeng Inc. American depositary shares, each representing two Class A ordinary shares", "XNYS"),
    ("XYZ", "Block, Inc.", "XNYS"),
)

# underlying symbol, product symbol, display name, exchange MIC, factor, issuer
PRODUCTS = (
    ("AAL", "AALG", "Themes ETF Trust Leverage Shares 2X Long AAL Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("AAOI", "AAOG", "Leverage Shares 2X Long AAOI Daily ETF", "BATS", "2", "Leverage Shares"),
    ("AAOI", "AAOX", "Tradr 2X Long AAOI Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("AAOI", "AAOZ", "Tradr 2X Short AAOI Daily ETF", "BATS", "-2", "Tradr ETFs"),
    ("ACHR", "ACHX", "Corgi ACHR 2x Daily ETF", "BATS", "2", "Corgi"),
    ("ACHR", "ARCX", "Tradr 2X Long ACHR Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("ACLS", "ACLZ", "Corgi ACLS 2x Daily ETF", "BATS", "2", "Corgi"),
    ("ACMR", "ACMM", "Corgi ACMR 2x Daily ETF", "BATS", "2", "Corgi"),
    ("AEHR", "AEHG", "Leverage Shares 2X Long AEHR Daily ETF", "BATS", "2", "Leverage Shares"),
    ("AFRM", "AFRU", "T-REX 2X Long AFRM Daily Target ETF", "BATS", "2", "T-REX"),
    ("AKAM", "AKAL", "T-REX 2X Long AKAM Daily Target ETF", "BATS", "2", "T-REX"),
    ("ALB", "ALBG", "Themes ETF Trust Leverage Shares 2X Long ALB Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("AMKR", "AMKL", "Defiance Daily Target 2X Long AMKR ETF", "BATS", "2", "Defiance"),
    ("AMKR", "AMKX", "Corgi AMKR 2x Daily ETF", "BATS", "2", "Corgi"),
    ("AMPX", "AMPU", "Defiance Daily Target 2X Long AMPX ETF", "BATS", "2", "Defiance"),
    ("ANET", "ANEL", "Tidal Trust II Defiance Daily Target 2x Long ANET ETF", "XNAS", "2", "Defiance"),
    ("APLD", "APLX", "Tradr 2X Long APLD Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("APLD", "APLZ", "Tradr 2X Short APLD Daily ETF", "BATS", "-2", "Tradr ETFs"),
    ("ARM", "ARMA", "Corgi ARM 2x Daily ETF", "BATS", "2", "Corgi"),
    ("ARM", "ARMG", "Themes ETF Trust Leverage Shares 2X Long ARM Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("ASTS", "ASTG", "Leverage Shares 2X Long ASTS Daily ETF", "BATS", "2", "Leverage Shares"),
    ("ASTS", "ASTN", "Defiance Daily Target 2X Short ASTS ETF", "BATS", "-2", "Defiance"),
    ("ASTS", "ASTT", "Corgi ASTS 2x Daily ETF", "BATS", "2", "Corgi"),
    ("ASTS", "ASTX", "Tradr 2X Long ASTS Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("ASTS", "ASTY", "Defiance Daily Target 2X Long ASTS ETF", "BATS", "2", "Defiance"),
    ("ASTS", "ASUP", "T-REX 2X Long ASTS Daily Target ETF", "BATS", "2", "T-REX"),
    ("AVAV", "AVXX", "Tidal Trust II Defiance Daily Target 2x Long AVAV ETF", "XNAS", "2", "Defiance"),
    ("AXTI", "AXTC", "Corgi AXTI 2x Daily ETF", "BATS", "2", "Corgi"),
    ("AXTI", "AXTL", "Leverage Shares 2X Long AXTI Daily ETF", "BATS", "2", "Leverage Shares"),
    ("AXTI", "AXTQ", "Tradr 2X Short AXTI Daily ETF", "BATS", "-2", "Tradr ETFs"),
    ("AXTI", "AXTU", "T-REX 2X Long AXTI Daily Target ETF", "BATS", "2", "T-REX"),
    ("AXTI", "AXTX", "Tradr 2X Long AXTI Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("BABA", "BABC", "Corgi BABA 2x Daily ETF", "BATS", "2", "Corgi"),
    ("BABA", "BABU", "Direxion Shares ETF Trust Direxion Daily BABA Bull 2X ETF", "XNAS", "2", "Direxion"),
    ("BABA", "BABX", "GraniteShares ETF Trust GraniteShares 2x Long BABA Daily ETF", "XNAS", "2", "GraniteShares"),
    ("BABA", "KBAB", "KraneShares Trust KraneShares 2x Long BABA Daily ETF", "XNAS", "2", "KraneShares"),
    ("BB", "BBUL", "GraniteShares ETF Trust GraniteShares 2x Long BB Daily ETF", "XNAS", "2", "GraniteShares"),
    ("BBAI", "BAIG", "Themes ETF Trust Leverage Shares 2X Long BBAI Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("BIDU", "BIDG", "Themes ETF Trust Leverage Shares 2X Long BIDU Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("BIDU", "KBDU", "KraneShares 2x Long BIDU Daily ETF", "XNAS", "2", "KraneShares"),
    ("BLSH", "BLSG", "Themes ETF Trust Leverage Shares 2X Long BLSH Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("BTDR", "BTDL", "GraniteShares ETF Trust GraniteShares 2x Long BTDR Daily ETF", "XNAS", "2", "GraniteShares"),
    ("BULL", "BULG", "Themes ETF Trust Leverage Shares 2X Long BULL Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("CAMT", "CAMC", "Corgi CAMT 2x Daily ETF", "BATS", "2", "Corgi"),
    ("CART", "CARX", "Corgi CART 2x Daily ETF", "BATS", "2", "Corgi"),
    ("CDNS", "CDNG", "Leverage Shares 2X Long CDNS Daily ETF", "BATS", "2", "Leverage Shares"),
    ("CEG", "CEGX", "Tradr 2X Long CEG Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("CIFR", "CIFC", "Corgi CIFR 2x Daily ETF", "BATS", "2", "Corgi"),
    ("CIFR", "CIFG", "Themes ETF Trust Leverage Shares 2X Long CIFR Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("CIFR", "CIFU", "T-REX 2X Long CIFR Daily Target ETF", "BATS", "2", "T-REX"),
    ("CLS", "CSEX", "Tradr 2X Long CLS Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("CLSK", "CLSX", "Tradr 2X Long CLSK Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("CORZ", "COZX", "Tradr 2X Long CORZ Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("CPNG", "CPNX", "Tradr 2X Long CPNG Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("CRML", "CRMU", "Themes ETF Trust Leverage Shares 2x Long CRML Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("CRML", "CRMX", "Tradr 2X Long CRML Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("CRUS", "CRUC", "Corgi CRUS 2x Daily ETF", "BATS", "2", "Corgi"),
    ("DJT", "DJTU", "T-REX 2X Long DJT Daily Target ETF", "BATS", "2", "T-REX"),
    ("DOCN", "OCNL", "T-REX 2X Long DOCN Daily Target ETF", "BATS", "2", "T-REX"),
    ("DUOL", "DUOG", "Themes ETF Trust Leverage Shares 2X Long DUOL Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("ECHO", "ECHX", "Themes ETF Trust Leverage Shares 2X Long ECHO Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("ENTG", "ENTL", "Leverage Shares 2X Long ENTG Daily ETF", "BATS", "2", "Leverage Shares"),
    ("EOSE", "EO", "Corgi EOSE 2x Daily ETF", "BATS", "2", "Corgi"),
    ("EOSE", "EOSU", "T-REX 2X Long EOSE Daily Target ETF", "BATS", "2", "T-REX"),
    ("ETN", "ETNG", "Leverage Shares 2X Long ETN Daily ETF", "BATS", "2", "Leverage Shares"),
    ("FCX", "FCXG", "Themes ETF Trust Leverage Shares 2x Long FCX Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("FIG", "FIGG", "Themes ETF Trust Leverage Shares 2x Long FIG Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("FIGR", "FGRU", "T-REX 2X Long FIGR Daily Target ETF", "BATS", "2", "T-REX"),
    ("FIX", "FIXX", "Leverage Shares 2X Long FIX Daily ETF", "BATS", "2", "Leverage Shares"),
    ("FLEX", "FLEL", "Leverage Shares 2X Long FLEX Daily ETF", "BATS", "2", "Leverage Shares"),
    ("FLY", "FLYT", "Tradr 2X Long FLY Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("FN", "FNG", "Leverage Shares 2X Long FN Daily ETF", "BATS", "2", "Leverage Shares"),
    ("FORM", "FOMG", "Leverage Shares 2X Long FORM Daily ETF", "BATS", "2", "Leverage Shares"),
    ("FPS", "FPSX", "Leverage Shares 2X Long FPS Daily ETF", "BATS", "2", "Leverage Shares"),
    ("FUTU", "FUTG", "Themes ETF Trust Leverage Shares 2x Long FUTU Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("GEMI", "GEMG", "Themes ETF Trust Leverage Shares 2X Long GEMI Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("GFS", "GFSG", "Leverage Shares 2X Long GFS Daily ETF", "BATS", "2", "Leverage Shares"),
    ("GLXY", "GLGG", "Themes ETF Trust Leverage Shares 2X Long GLXY Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("GLXY", "GLX", "Corgi GLXY 2x Daily ETF", "BATS", "2", "Corgi"),
    ("GLXY", "GLXU", "T-REX 2X Long GLXY Daily Target ETF", "BATS", "2", "T-REX"),
    ("GME", "GMEC", "Corgi GME 2x Daily ETF", "BATS", "2", "Corgi"),
    ("GME", "GMEU", "T-REX 2X Long GME Daily Target ETF", "BATS", "2", "T-REX"),
    ("GRAB", "GRAG", "Themes ETF Trust Leverage Shares 2X Long GRAB Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("HIMS", "HIMC", "Corgi HIMS 2x Daily ETF", "BATS", "2", "Corgi"),
    ("HIMS", "HIMZ", "Tidal Trust II Defiance Daily Target 2X Long HIMS ETF", "XNAS", "2", "Defiance"),
    ("HON", "HONG", "Leverage Shares 2X Long HON Daily ETF", "BATS", "2", "Leverage Shares"),
    ("HUT", "HUTG", "Themes ETF Trust Leverage Shares 2X Long HUT Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("IBM", "IBX", "Tradr 2X Long IBM Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("INFQ", "INFH", "Defiance Daily Target 2X Long INFQ ETF", "BATS", "2", "Defiance"),
    ("IONQ", "IONC", "Corgi IONQ 2x Daily ETF", "BATS", "2", "Corgi"),
    ("IONQ", "IONL", "GraniteShares ETF Trust GraniteShares 2x Long IONQ Daily ETF", "XNAS", "2", "GraniteShares"),
    ("IONQ", "IONX", "Tidal Trust II Defiance Daily Target 2X Long IONQ ETF", "XNAS", "2", "Defiance"),
    ("IONQ", "IONZ", "Tidal Trust II Defiance Daily Target 2x Short IONQ ETF", "XNAS", "-2", "Defiance"),
    ("ISRG", "ISUL", "GraniteShares ETF Trust GraniteShares 2x Long ISRG Daily ETF", "XNAS", "2", "GraniteShares"),
    ("JBL", "JBLG", "Leverage Shares 2X Long JBL Daily ETF", "BATS", "2", "Leverage Shares"),
    ("JD", "KJD", "KraneShares Trust KraneShares 2x Long JD Daily ETF", "XNAS", "2", "KraneShares"),
    ("JOBY", "JOBC", "Corgi JOBY 2x Daily ETF", "BATS", "2", "Corgi"),
    ("JOBY", "JOBX", "Tradr 2X Long JOBY Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("KEEL", "KEEX", "Defiance Daily Target 2x Long KEEL ETF", "BATS", "2", "Defiance"),
    ("KEYS", "KEYG", "Leverage Shares 2X Long KEYS Daily ETF", "BATS", "2", "Leverage Shares"),
    ("KEYS", "KEYX", "Corgi KEYS 2x Daily ETF", "BATS", "2", "Corgi"),
    ("KTOS", "KTUP", "T-REX 2X Long KTOS Daily Target ETF", "BATS", "2", "T-REX"),
    ("LASR", "LASC", "Corgi LASR 2x Daily ETF", "BATS", "2", "Corgi"),
    ("LEU", "LEUX", "Tradr 2X Long LEU Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("LMT", "LMTL", "Direxion Shares ETF Trust Direxion Daily LMT Bull 2X ETF", "XNAS", "2", "Direxion"),
    ("LRN", "LRNX", "Corgi LRN 2x Daily ETF", "BATS", "2", "Corgi"),
    ("LUNR", "LUNL", "Defiance Daily Target 2X Long LUNR ETF", "BATS", "2", "Defiance"),
    ("LWLG", "LWLX", "Tradr 2X Long LWLG Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("MARA", "MHX", "Corgi MARA 2x Daily ETF", "BATS", "2", "Corgi"),
    ("MARA", "MRAL", "GraniteShares ETF Trust GraniteShares 2x Long MARA Daily ETF", "XNAS", "2", "GraniteShares"),
    ("MCHP", "MCHG", "Leverage Shares 2X Long MCHP Daily ETF", "BATS", "2", "Leverage Shares"),
    ("MCHP", "MCHU", "Tradr 2X Long MCHP Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("MELI", "KMLI", "KraneShares Trust KraneShares 2x Long MELI Daily ETF", "XNAS", "2", "KraneShares"),
    ("MNST", "MNSX", "Corgi MNST 2x Daily ETF", "BATS", "2", "Corgi"),
    ("MP", "MPG", "Themes ETF Trust Leverage Shares 2X Long MP Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("MPWR", "MPWC", "Corgi MPWR 2x Daily ETF", "BATS", "2", "Corgi"),
    ("MPWR", "MPWX", "Tradr 2X Long MPWR Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("MRAM", "MRAX", "Tradr 2X Long MRAM Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("MSI", "MSIX", "Corgi MSI 2x Daily ETF", "BATS", "2", "Corgi"),
    ("MTSI", "MTSG", "Leverage Shares 2X Long MTSI Daily ETF", "BATS", "2", "Leverage Shares"),
    ("MXL", "MXLL", "Leverage Shares 2X Long MXL Daily ETF", "BATS", "2", "Leverage Shares"),
    ("NEM", "NEMG", "Themes ETF Trust Leverage Shares 2x Long NEM Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("NET", "NETG", "Themes ETF Trust Leverage Shares 2X Long NET Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("NIO", "NIOG", "Themes ETF Trust Leverage Shares 2X Long NIO Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("NOK", "LNOK", "Defiance Daily Target 2X Long NOK ETF", "BATS", "2", "Defiance"),
    ("NTAP", "NTAL", "GraniteShares ETF Trust GraniteShares 2x Long NTAP Daily ETF", "XNAS", "2", "GraniteShares"),
    ("NVO", "NVOC", "Corgi NVO 2x Daily ETF", "BATS", "2", "Corgi"),
    ("NVO", "NVOX", "Defiance Daily Target 2x Long NVO ETF", "ARCX", "2", "Defiance"),
    ("NVTS", "NVTC", "Corgi NVTS 2x Daily ETF", "BATS", "2", "Corgi"),
    ("NVTS", "NVTX", "Tradr 2X Long NVTS Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("NXPI", "NXPG", "Leverage Shares 2X Long NXPI Daily ETF", "BATS", "2", "Leverage Shares"),
    ("NXPI", "NXPX", "Tradr 2X Long NXPI Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("OKLO", "OKLC", "Corgi OKLO 2x Daily ETF", "BATS", "2", "Corgi"),
    ("OKLO", "OKLL", "Tidal Trust II Defiance Daily Target 2x Long OKLO ETF", "XNAS", "2", "Defiance"),
    ("OKTA", "OKTG", "Themes ETF Trust Leverage Shares 2X Long OKTA Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("ON", "ONG", "Leverage Shares 2X Long ON Daily ETF", "BATS", "2", "Leverage Shares"),
    ("ON", "ONX", "Tradr 2X Long ON Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("ONDS", "ONDC", "Corgi ONDS 2x Daily ETF", "BATS", "2", "Corgi"),
    ("ONDS", "ONDG", "Themes ETF Trust Leverage Shares 2X Long ONDS Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("ONDS", "ONDL", "Defiance Daily Target 2X Long ONDS ETF", "BATS", "2", "Defiance"),
    ("ONDS", "ONDU", "Tradr 2X Long ONDS Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("ONTO", "ONTX", "Corgi ONTO 2x Daily ETF", "BATS", "2", "Corgi"),
    ("OPEN", "OPEG", "Themes ETF Trust Leverage Shares 2X Long OPEN Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("OPEN", "OPEX", "Tradr 2X Long OPEN Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("OSCR", "OSCX", "Tidal Trust II Defiance Daily Target 2x Long OSCR ETF", "XNAS", "2", "Defiance"),
    ("OSS", "OSSL", "Defiance Daily Target 2X Long OSS ETF", "BATS", "2", "Defiance"),
    ("OUST", "OUSL", "Defiance Daily Target 2X Long OUST ETF", "BATS", "2", "Defiance"),
    ("P", "PUL", "GraniteShares ETF Trust GraniteShares 2x Long P Daily ETF", "XNAS", "2", "GraniteShares"),
    ("PBR", "PBRG", "Themes ETF Trust Leverage Shares 2X Long PBR Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("PDD", "KPDD", "KraneShares Trust KraneShares 2x Long PDD Daily ETF", "XNAS", "2", "KraneShares"),
    ("PDD", "PDDL", "GraniteShares ETF Trust GraniteShares 2x Long PDD Daily ETF", "XNAS", "2", "GraniteShares"),
    ("PENG", "PENU", "T-REX 2X Long PENG Daily Target ETF", "BATS", "2", "T-REX"),
    ("PL", "PLU", "Defiance Daily Target 2x Long PL ETF", "BATS", "2", "Defiance"),
    ("PLUG", "PLUL", "Themes ETF Trust Leverage Shares 2X Long PLUG Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("POET", "POEL", "Defiance Daily Target 2X Long POET ETF", "BATS", "2", "Defiance"),
    ("PONY", "PONX", "Tradr 2X Long PONY Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("PURR", "PUR", "Tidal Trust II Defiance Daily Target 2X Long PURR ETF", "XNAS", "2", "Defiance"),
    ("PYPL", "PYPG", "Themes ETF Trust Leverage Shares 2X Long PYPL Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("PYPL", "PYPU", "Direxion Daily PYPL Bull 2X ETF", "ARCX", "2", "Direxion"),
    ("QBTS", "QBTX", "Tradr 2X Long QBTS Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("QBTS", "QBTZ", "Tidal Trust II Defiance Daily Target 2x Short QBTS ETF", "XNAS", "-2", "Defiance"),
    ("QBTS", "QUA", "Corgi QBTS 2x Daily ETF", "BATS", "2", "Corgi"),
    ("QNT", "QNTU", "Tradr 2X Long QNT Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("QS", "QSU", "Defiance Daily Target 2X Long QS ETF", "ARCX", "2", "Defiance"),
    ("QUBT", "QUBX", "Tradr 2X Long QUBT Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("RBLX", "RBLU", "T-REX 2X Long RBLX Daily Target ETF", "BATS", "2", "T-REX"),
    ("RCAT", "RCAX", "Tidal Trust II Defiance Daily Target 2x Long RCAT ETF", "XNAS", "2", "Defiance"),
    ("RDDT", "RDDC", "Corgi RDDT 2x Daily ETF", "BATS", "2", "Corgi"),
    ("RDDT", "RDTL", "GraniteShares ETF Trust GraniteShares 2x Long RDDT Daily ETF", "XNAS", "2", "GraniteShares"),
    ("RDW", "RDWU", "T-REX 2X Long RDW Daily Target ETF", "BATS", "2", "T-REX"),
    ("RGTI", "RGTC", "Corgi RGTI 2x Daily ETF", "BATS", "2", "Corgi"),
    ("RGTI", "RGTU", "Tradr 2X Long RGTI Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("RGTI", "RGTX", "Tidal Trust II Defiance Daily Target 2X Long RGTI ETF", "XNAS", "2", "Defiance"),
    ("RGTI", "RGTZ", "Tidal Trust II Defiance Daily Target 2x Short RGTI ETF", "XNAS", "-2", "Defiance"),
    ("RIOT", "RIOX", "Defiance Daily Target 2X Long RIOT ETF", "ARCX", "2", "Defiance"),
    ("RIVN", "RIVC", "Corgi RIVN 2x Daily ETF", "BATS", "2", "Corgi"),
    ("RIVN", "RVNL", "GraniteShares ETF Trust GraniteShares 2x Long RIVN Daily ETF", "XNAS", "2", "GraniteShares"),
    ("RMBS", "RMBC", "Corgi RMBS 2x Daily ETF", "BATS", "2", "Corgi"),
    ("RMBS", "RMBX", "Tradr 2X Long RMBS Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("RTX", "RTXG", "Themes ETF Trust Leverage Shares 2X Long RTX Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("SBET", "SBTU", "T-REX 2X Long SBET Daily Target ETF", "BATS", "2", "T-REX"),
    ("SIMO", "SIMX", "Corgi SIMO 2x Daily ETF", "BATS", "2", "Corgi"),
    ("SITM", "SITX", "Tradr 2X Long SITM Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("SMR", "SMRX", "Corgi SMR 2x Daily ETF", "BATS", "2", "Corgi"),
    ("SMR", "SMU", "Tradr 2X Long SMR Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("SMR", "SMUP", "T-REX 2X Long SMR Daily Target ETF", "BATS", "2", "T-REX"),
    ("SMR", "SMZ", "Tradr 2X Short SMR Daily ETF", "BATS", "-2", "Tradr ETFs"),
    ("SMTC", "SMTG", "Leverage Shares 2X Long SMTC Daily ETF", "BATS", "2", "Leverage Shares"),
    ("SNAP", "SNAG", "Themes ETF Trust Leverage Shares 2x Long SNAP Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("SOFI", "SOFA", "Direxion Shares ETF Trust Direxion Daily SOFI Bull 2X ETF", "XNAS", "2", "Direxion"),
    ("SOFI", "SOFC", "Corgi SOFI 2x Daily ETF", "BATS", "2", "Corgi"),
    ("SOFI", "SOFX", "Tidal Trust II Defiance Daily Target 2X Long SOFI ETF", "XNAS", "2", "Defiance"),
    ("SOUN", "SOUX", "Tidal Trust II Defiance Daily Target 2X Long SOUN ETF", "XNAS", "2", "Defiance"),
    ("SPOT", "SPOG", "Themes ETF Trust Leverage Shares 2X Long SPOT Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("STM", "STMX", "Leverage Shares 2X Long STM Daily ETF", "BATS", "2", "Leverage Shares"),
    ("STRL", "STLL", "Leverage Shares 2X Long STRL Daily ETF", "BATS", "2", "Leverage Shares"),
    ("TDC", "TDCL", "GraniteShares ETF Trust GraniteShares 2x Long TDC Daily ETF", "XNAS", "2", "GraniteShares"),
    ("TE", "TEUP", "T-REX 2X Long TE Daily Target ETF", "BATS", "2", "T-REX"),
    ("TEL", "TELG", "Leverage Shares 2X Long TEL Daily ETF", "BATS", "2", "Leverage Shares"),
    ("TEM", "TEMC", "Corgi TEM 2x Daily ETF", "BATS", "2", "Corgi"),
    ("TEM", "TEMT", "Tradr 2X Long TEM Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("TER", "TERC", "Corgi TER 2x Daily ETF", "BATS", "2", "Corgi"),
    ("TER", "TERG", "Themes ETF Trust Leverage Shares 2X Long TER Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("TPL", "TPLX", "Corgi TPL 2x Daily ETF", "BATS", "2", "Corgi"),
    ("TSEM", "TSEG", "Leverage Shares 2X Long TSEM Daily ETF", "BATS", "2", "Leverage Shares"),
    ("TSEM", "TSEU", "Tradr 2X Long TSEM Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("TTD", "TTDU", "T-REX 2X Long TTD Daily Target ETF", "BATS", "2", "T-REX"),
    ("TTMI", "TTMX", "Tradr 2X Long TTMI Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("U", "UNX", "Tradr 2X Long U Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("UCTT", "UCTX", "Corgi UCTT 2x Daily ETF", "BATS", "2", "Corgi"),
    ("UEC", "UECG", "Themes ETF Trust Leverage Shares 2x Long UEC Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("UMAC", "UMAL", "Defiance Daily Target 2X Long UMAC ETF", "BATS", "2", "Defiance"),
    ("UMC", "UMCU", "Tradr 2X Long UMC Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("UMC", "UMCX", "Corgi UMC 2x Daily ETF", "BATS", "2", "Corgi"),
    ("UPST", "UPSC", "Corgi UPST 2x Daily ETF", "BATS", "2", "Corgi"),
    ("UPST", "UPSX", "Tradr 2X Long UPST Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("USAR", "USAX", "Tradr 2X Long USAR Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("USAR", "USGG", "Themes ETF Trust Leverage Shares 2X Long USAR Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("UUUU", "UUUC", "Corgi UUUU 2x Daily ETF", "BATS", "2", "Corgi"),
    ("UUUU", "UUUG", "Themes ETF Trust Leverage Shares 2X Long UUUU Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("VALE", "VALG", "Themes ETF Trust Leverage Shares 2X Long VALE Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("VELO", "VELL", "Defiance Daily Target 2X Long VELO ETF", "BATS", "2", "Defiance"),
    ("VIAV", "VIAG", "Leverage Shares 2X Long VIAV Daily ETF", "BATS", "2", "Leverage Shares"),
    ("VST", "VSTL", "Tidal Trust II Defiance Daily Target 2X Long VST ETF", "XNAS", "2", "Defiance"),
    ("WULF", "WULX", "Tradr 2X Long WULF Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("WYFI", "WYFL", "Defiance Daily Target 2X Long WYFI ETF", "BATS", "2", "Defiance"),
    ("XNDU", "XNDX", "Tradr 2X Long XNDU Daily ETF", "BATS", "2", "Tradr ETFs"),
    ("XPEV", "XPEG", "Themes ETF Trust Leverage Shares 2X Long XPEV Daily ETF", "XNAS", "2", "Leverage Shares"),
    ("XYZ", "XYZG", "Themes ETF Trust Leverage Shares 2X Long XYZ Daily ETF", "XNAS", "2", "Leverage Shares"),
)


def upgrade() -> None:
    underlyings = sa.table(
        "underlyings",
        sa.column("id", sa.String),
        sa.column("symbol", sa.String),
        sa.column("display_name", sa.String),
        sa.column("instrument_type", sa.String),
        sa.column("exchange_mic", sa.String),
        sa.column("currency", sa.String),
        sa.column("active", sa.Boolean),
        sa.column("profit_ratio_available", sa.Boolean),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    products = sa.table(
        "leveraged_products",
        sa.column("id", sa.String),
        sa.column("relationship_id", sa.String),
        sa.column("symbol", sa.String),
        sa.column("display_name", sa.String),
        sa.column("exchange_mic", sa.String),
        sa.column("underlying_id", sa.String),
        sa.column("signed_leverage", sa.Numeric),
        sa.column("issuer", sa.String),
        sa.column("direction", sa.String),
        sa.column("active", sa.Boolean),
        sa.column("objective_period", sa.String),
        sa.column("authoritative_source", sa.String),
        sa.column("verified_at", sa.DateTime(timezone=True)),
        sa.column("effective_from", sa.Date),
        sa.column("effective_to", sa.Date),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    connection = op.get_bind()
    connection.execute(
        insert(underlyings)
        .values([_underlying_row(*item) for item in UNDERLYINGS])
        .on_conflict_do_nothing(index_elements=["symbol"])
    )
    connection.execute(
        insert(products)
        .values([_product_row(*item) for item in PRODUCTS])
        .on_conflict_do_nothing(index_elements=["symbol"])
    )


def _underlying_row(
    symbol: str,
    name: str,
    exchange_mic: str,
) -> dict[str, object]:
    return {
        "id": _instrument_id(symbol, exchange_mic),
        "symbol": symbol,
        "display_name": name,
        "instrument_type": "stock",
        "exchange_mic": exchange_mic,
        "currency": "USD",
        "active": True,
        "profit_ratio_available": False,
        "created_at": VERIFIED_AT,
        "updated_at": VERIFIED_AT,
    }


def _product_row(
    underlying_symbol: str,
    symbol: str,
    name: str,
    exchange_mic: str,
    leverage: str,
    issuer: str,
) -> dict[str, object]:
    underlying = next(item for item in UNDERLYINGS if item[0] == underlying_symbol)
    leverage_id = leverage.replace("-", "n").replace(".", "p")
    return {
        "id": _instrument_id(symbol, exchange_mic),
        "relationship_id": (
            f"rel_{_slug(underlying_symbol)}_{_slug(symbol)}_{leverage_id}x"
        ),
        "symbol": symbol,
        "display_name": name,
        "exchange_mic": exchange_mic,
        "underlying_id": _instrument_id(underlying[0], underlying[2]),
        "signed_leverage": leverage,
        "issuer": issuer,
        "direction": "LONG" if not leverage.startswith("-") else "INVERSE",
        "active": True,
        "objective_period": "daily",
        "authoritative_source": ISSUER_SOURCES[issuer],
        "verified_at": VERIFIED_AT,
        "effective_from": EFFECTIVE_FROM,
        "effective_to": None,
        "created_at": VERIFIED_AT,
        "updated_at": VERIFIED_AT,
    }


def _instrument_id(symbol: str, exchange_mic: str) -> str:
    return f"ins_{_slug(symbol)}_{exchange_mic.lower()}"


def _slug(symbol: str) -> str:
    return symbol.lower().replace(".", "_")


def downgrade() -> None:
    products = sa.table("leveraged_products", sa.column("symbol", sa.String))
    underlyings = sa.table("underlyings", sa.column("symbol", sa.String))
    op.execute(
        products.delete().where(
            products.c.symbol.in_(sorted(item[1] for item in PRODUCTS))
        )
    )
    op.execute(
        underlyings.delete().where(
            underlyings.c.symbol.in_(sorted(item[0] for item in UNDERLYINGS))
        )
    )

